# Generated by Django 3.0.8 on 2020-10-01 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hexa', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_desc', models.CharField(max_length=150)),
                ('detail_desc', models.TextField()),
                ('category', models.CharField(choices=[('L', 'Living room'), ('B', 'Bedroom'), ('K', 'Kitchen & dining')], default='L', max_length=2)),
                ('in_stock', models.BooleanField(default=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('colors', models.ManyToManyField(to='products.Color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='no-picture.png', upload_to=products.models.get_upload_location)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
