# Generated by Django 3.0.8 on 2020-10-01 16:47

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='no-picture.png', upload_to=products.models.get_upload_location)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='products.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductPicture',
        ),
    ]
